Integração Componente gráfico do Indicador
artursanntos/vfoods pull request #20
Opened 2023-10-01 14:01 UTC by jmlv-git

Principais ações realizadas:
1. Entendimento dos tipos de dados que estavam transitando pela aplicação;
2. Requisição do back;
3. Adaptação ao formato da resposta do back.

2023-10-01 15:51 UTC, nathaliafab approved these changes
Pra mim parece tudo ok, foi testado já?

2023-10-01 21:15 UTC, artursanntos requested changes
Tudo certo quanto ao código, talvez fosse bom dar uma olhada nesse arquivo que eu pontuei só antes de dar merge

2023-10-01 21:15 UTC, artursanntos commented on vite.config.ts.timestamp-1696095715514-3b4069a2a49ca.mjs
Eu não entendi esse arquivo aqui, aí joguei no google e descobri que ele já deu problema pra uma galera em alguns fóruns. Eu não consegui chegar a uma conclusão se é seguro apagar ele. Eu vi umas pessoas falando sobre adicionar ele no .gitignore nesse modelo `vite.config.ts.timestamp-*.mjs`, mas realmente não sei se é seguro. Talvez não tenha problema nenhum, mas se der pra tu dar uma olhada também. Eu caí nessa discussão aqui ó https://github.com/vitejs/vite/issues/9470.

2023-10-02 06:00 UTC, gugaccampos approved these changes
Por mim ta tudo certo joão, não sei qual era o arquivo q artur tava falando que tu inseriu, mas acho que tu ja tirou ele, n vou dar merge agora já que artur que pediu a mudança acho q ele precisa aprovar dnv, mas ta tudo certo por mim!

2023-10-02 16:40 UTC, artursanntos approved these changes

2023-10-02 16:41 UTC, merged

2023-10-02 16:41 UTC, artursanntos commented
Top